baseurl = "joehandzik.github.io"
languageCode = "en-us"
title = "Handzik.io"

[params]
twitter = "http://www.twitter.com/joehandzik"
linkedin = "http://www.linkedin.com/in/joehandzik"
facebook = "http://www.facebook.com/JosephTHandzik"
github = "http://www.github.com/joehandzik"
