languageCode = "en-us"
title = "Handzik.io"

[params]
twitter = "www.twitter.com/joehandzik"
linkedin = "www.linkedin.com/in/joehandzik"
facebook = "www.facebook.com/JosephTHandzik"
github = "www.github.com/joehandzik"
